/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhm_dht11native_DHT11Native_State */

#ifndef _Included_com_zhm_dht11native_DHT11Native_State
#define _Included_com_zhm_dht11native_DHT11Native_State
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
