/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhm_dht11native_DHT11Native */

#ifndef _Included_com_zhm_dht11native_DHT11Native
#define _Included_com_zhm_dht11native_DHT11Native
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zhm_dht11native_DHT11Native_MAX_GPIO
#define com_zhm_dht11native_DHT11Native_MAX_GPIO 30L
/*
 * Class:     com_zhm_dht11native_DHT11Native
 * Method:    readNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zhm_dht11native_DHT11Native_readNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
